language : "node_js"
node_js :
  - "8"
cache:
 directories:
  - "node_modules"
env:
  global:
    - export NODE_ENV=test

script:
  - yarn test

before_deploy:
  - yarn install
  - yarn global add now
  - now rm react-nyne -y --token $NOW_TOKEN_ONE || true

deploy:
  provider: script
  script: now --token $NOW_TOKEN_ONE --public
  skip_cleanup: true
  on:
    branch: develop
    master: true

after_success:
  - yarn run coveralls
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info
